### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Trinadhbabu**
I did changes to D3 Visualization (https://www.jasondavies.com/coffee-wheel/) to make work in MicroStrategy. Please review and Upload it to the repository

### CODE REVIEW

**Comment by PeipeiChen** [comment]
Hi,

Thanks for sharing the custom viz with us. Would you please upload a folder instead of the zip file, similar to other existing plugins in the repository? 

Thanks,
Emma

**Comment by PeipeiChen** [comment]
Hi, I have uploaded the plugin folder for the ZoomableSunburst. We would appreciate it if you can  create a README.md for this custom viz so that we will know this viz works. You can refer to the readme.md in other plugins as the example.

**Comment by Trinadhbabu** [comment]
I am unable to upload the readme.md file. can you please create it for me.
details are given below.
- *Visualization name : *Zoomable Sunburst
- _Visualization version:_ N/A
- _Visualization screenshot_ (800x600 png or jpeg): Attached
- _Description_
  - _General description:_ This is an example of using
    d3.layout.partition
    http://github.com/mbostock/d3/wiki/Partition-Layout to generate a
    zoomable sunburst tree derived from hierarchical data. A sunburst tree
    http://www.cc.gatech.edu/gvu/ii/sunburst/ is a radial space-filling
    visualisation, analagous to an icicle tree.
  - _Link to visualization information in Wikipedia or other relevant
    sites if available:_ https://www.jasondavies.com/coffee-wheel/
  - _Object requirements (number of attributes, metrics; required data
    types):_ one or more Attributes, only one Metric
    -
  
  Contributor: Trinadh Singaladevi.
  
  Contributor's Contact Info.: trinadhbabu.s@gmail.com
  
  Contributor's Orgnization: Nielsen.
  
  Original Author: jason davies jason@jasondavies.com
  
  Original Author's Orgnization:
  
  Original Author's Contact Info.:jason@jasondavies.com

Regards,
Trinadh S.

**Comment by Trinadhbabu** [comment]
Hello Team,

I have uploaded Zoomable suburst in MSTR Github. which is working
perfectly. Below is the link. But now this link says, its depricated. but
my visualization is not published anywhere. I am missing something? where
can I find the Below visualization?

https://github.com/mstr-dev/Visualization-Plugins-Deprecated/tree/master/ZoomableSunburst

Regards,
Trinadh S

On Wed, Jun 1, 2016 at 6:20 PM, Trinadh Singaladevi <trinadhbabu.s@gmail.com

**Comment by tiagosiebler** [comment]
Hi @Trinadhbabu, the github visualizations repository was deprecated a while back, instead current the reference for sample visualizations is the visualization gallery: https://community.microstrategy.com/s/gallery

Thanks,
Tiago

**Comment by PeipeiChen** [comment]
Hi @Trinadhbabu, for now you can still find the plugin from my personal repo: 
https://github.com/PeipeiChen/Visualization-Plugins

Thanks,
Emma

**Comment by Trinadhbabu** [comment]
Thank you for the quick reply. Here I cannot find the Zoomable sunburst. I
can see it only in the below link

https://github.com/PeipeiChen/Visualization-Plugins.

But this is a personal link. will this also be deprecated? is Zoomable
sunburst is going to place in the
 https://community.microstrategy.com/s/gallery?

Regards,
Trinadh S

Regards,
Trinadh

**Comment by PeipeiChen** [comment]
@Trinadhbabu 
I may keep this repo for a while but can't promise to keep it long. 
For the Visualization Gallery, it is maintained by another team and I've already sent an email to ask the question. 

Will let you know if I get further information. 

Thanks,
Emma

**Comment by Trinadhbabu** [comment]
Thank you.

**Pull request merged**
